# Generated by Django 3.1.3 on 2020-11-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
