# Generated by Django 3.1.3 on 2020-11-28 01:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_itempicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempicture',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
