# Generated by Django 3.1.3 on 2020-12-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20201128_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fastest_delivery',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slowest_delivery',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='usps_option',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
