# Generated by Django 3.1.3 on 2020-12-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20201201_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
