# Generated by Django 3.1.3 on 2022-12-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_item_shipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('stripe_acct_id', models.CharField(max_length=255)),
            ],
        ),
    ]
