# Generated by Django 3.1.3 on 2020-11-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
