# Generated by Django 3.1.3 on 2020-12-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
            ],
        ),
    ]
