# Generated by Django 3.1.3 on 2020-11-24 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_twofaverified_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
    ]
