# Generated by Django 3.1.3 on 2020-11-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_authorizeddevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizeddevice',
            name='code',
            field=models.CharField(default=0, max_length=7, unique=True),
            preserve_default=False,
        ),
    ]
