# Generated by Django 3.1.3 on 2020-11-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_authorizeddevice_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizeddevice',
            name='code',
        ),
    ]
